In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
datetime_index = pd.date_range(start = "2025-01-01", periods = 4, freq = 'h')
sales_data = [100, 200, 300, 400]
df = pd.Series(sales_data, index = datetime_index)
df

2025-01-01 00:00:00    100
2025-01-01 01:00:00    200
2025-01-01 02:00:00    300
2025-01-01 03:00:00    400
Freq: h, dtype: int64

# Introduction: Exercise 1

In [11]:
data = {
    "name": ['iPhone', 'Charger', 'Espresso', 'TV', 'Kettle'],
    'brand': ['Apple', 'Samsung', 'Philips', 'Xiaomi', 'Huawei'],
    'price': [1500, 200, 5000, 5000, 658],
    'count': [2, 10, 4, 1, 14],
    'sales': [300000, 25000, 196000, 99000, 69986]
}
dt = pd.date_range(start = "2025-01-10", periods = 5, freq = 'd')
df = pd.DataFrame(data, index = dt)
df

                name    brand  price  count   sales
2025-01-10    iPhone    Apple   1500      2  300000
2025-01-11   Charger  Samsung    200     10   25000
2025-01-12  Espresso  Philips   5000      4  196000
2025-01-13        TV   Xiaomi   5000      1   99000
2025-01-14    Kettle   Huawei    658     14   69986

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5 entries, 2025-01-10 to 2025-01-14
Freq: D
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   brand   5 non-null      object
 2   price   5 non-null      int64
 3   count   5 non-null      int64
 4   sales   5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 240.0+ bytes

In [13]:
df['sales'].sum()

689986

In [21]:
city = ['Chicago', 'London', 'New York', None, 'Atlanta']
df['city'] = city
df

                name    brand  price  count   sales      city
2025-01-10    iPhone    Apple   1500      2  300000   Chicago
2025-01-11   Charger  Samsung    200     10   25000    London
2025-01-12  Espresso  Philips   5000      4  196000  New York
2025-01-13        TV   Xiaomi   5000      1   99000      None
2025-01-14    Kettle   Huawei    658     14   69986   Atlanta

# Introduction: Exercise 2

In [24]:
ind = pd.date_range(start = "2025-01-01", periods = 7, freq = 'd')
crypto_data = [43500, 44200, 41700, 46000, 45500, 43800, 47000]
crypto_df = pd.Series(crypto_data, index = ind)
crypto_df

2025-01-01    43500
2025-01-02    44200
2025-01-03    41700
2025-01-04    46000
2025-01-05    45500
2025-01-06    43800
2025-01-07    47000
Freq: D, dtype: int64

In [26]:
print("Min:", crypto_df.min())
print("Max:", crypto_df.max())
print("Mean:", crypto_df.mean())

Min: 41700
Max: 47000
Mean: 44528.57142857143

In [29]:
cdf = crypto_df.to_frame()
new_price = [43501, 44201, 41701, 46001, 45501, 43810, 47001]
cdf['new_price'] = new_price
cdf = cdf.rename_axis("date").rename(columns = {cdf.columns[0]: 'old_price'})
cdf

            old_price  new_price
date
2025-01-01      43500      43501
2025-01-02      44200      44201
2025-01-03      41700      41701
2025-01-04      46000      46001
2025-01-05      45500      45501
2025-01-06      43800      43810
2025-01-07      47000      47001

In [37]:
cdf.rolling(window = 3).mean()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

               old_price     new_price
date
2025-01-01           NaN           NaN
2025-01-02           NaN           NaN
2025-01-03  43133.333333  43134.333333
2025-01-04  43966.666667  43967.666667
2025-01-05  44400.000000  44401.000000
2025-01-06  45100.000000  45104.000000
2025-01-07  45433.333333  45437.333333

# DataFrame/Series: Exercise 1

In [24]:
df = pd.read_csv("/kaggle/input/youtube-clips/youtube_clips.csv", sep = '\t')
df

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,title,commentCount,dislikeCount,likeCount,music_style,performer,viewCount,commentators_uniq,comments_obscene_cnt,video_age
0,"""#2Маши ""Свободные линии""",34.0,43.0,1402.0,popsa,2маши,214301.0,24.0,0.0,1141
1,"""ALARM"" СЕРГЕЙ ЛАЗАРЕВ ( SERGEY LAZAREV )",NaN,690.0,10532.0,popsa,лазарев,2221419.0,NaN,NaN,3217
2,"""EARTH SONG"" SERGEY LAZAREV. DEDICATED TO MIC...",26.0,10.0,269.0,popsa,лазарев,40327.0,23.0,0.0,3546
3,"""Earth song"" премия МУЗ-тВ 2010 (LIVE)",12.0,7.0,163.0,popsa,лазарев,11907.0,11.0,0.0,3189
4,"""FAKE"" СЕРГЕЙ ЛАЗАРЕВ (SERGEY)",46.0,19.0,597.0,popsa,лазарев,91483.0,33.0,1.0,3361
...,...,...,...,...,...,...,...,...,...,...
19119,♫♪Мы расстаемся ♫♪ Бутырка new2019,2.0,0.0,11.0,shanson,бутырка,1107.0,NaN,NaN,44
19120,❤ 2 ЧАСА ❤ МОЦАРТ Для Младенцев - Колыбельная ...,94.0,431.0,1837.0,classic,classical_channel,391836.0,37.0,1.0,239
19121,モスクワライブショー ' 17,4872.0,15494.0,30603.0,rap,элджей,1187340.0,1788.0,352.0,339
19122,舞梅鬼 - 新年好宝贝 / Mumiy Troll - Happy New Year ...,59.0,10.0,260.0,rock,мумий_тролль,10147.0,19.0,0.0,997
19123,🎄#премьера песни!!! 2019г(вы не спешите говори...,1.0,0.0,22.0,shanson,бутырка,1566.0,NaN,NaN,65

In [25]:
df.head(10)

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,title,commentCount,dislikeCount,likeCount,music_style,performer,viewCount,commentators_uniq,comments_obscene_cnt,video_age
0,"""#2Маши ""Свободные линии""",34.0,43.0,1402.0,popsa,2маши,214301.0,24.0,0.0,1141
1,"""ALARM"" СЕРГЕЙ ЛАЗАРЕВ ( SERGEY LAZAREV )",NaN,690.0,10532.0,popsa,лазарев,2221419.0,NaN,NaN,3217
2,"""EARTH SONG"" SERGEY LAZAREV. DEDICATED TO MIC...",26.0,10.0,269.0,popsa,лазарев,40327.0,23.0,0.0,3546
3,"""Earth song"" премия МУЗ-тВ 2010 (LIVE)",12.0,7.0,163.0,popsa,лазарев,11907.0,11.0,0.0,3189
4,"""FAKE"" СЕРГЕЙ ЛАЗАРЕВ (SERGEY)",46.0,19.0,597.0,popsa,лазарев,91483.0,33.0,1.0,3361
5,"""Feelin High"" Сергей Лазарев Sergey Lazarev live",7.0,7.0,87.0,popsa,лазарев,9217.0,6.0,0.0,3179
6,"""Girlfriend"" Сергей Лазарев (SERGEY)",88.0,69.0,1566.0,popsa,лазарев,449891.0,63.0,1.0,4013
7,"""Heartbeat"" Сергей Лазарев (Sergey Lazarev)",168.0,101.0,4091.0,popsa,лазарев,763611.0,130.0,0.0,2948
8,"""Hey Tovarish"" Video Shooting",10.0,1.0,34.0,rock,мумий_тролль,3815.0,9.0,0.0,2539
9,"""LAZERBOY"" Сергей Лазарев (SERGEY) feat. TИМАТ...",422.0,229.0,4137.0,popsa,лазарев,629212.0,223.0,6.0,3765

In [26]:
df.tail(5)

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,title,commentCount,dislikeCount,likeCount,music_style,performer,viewCount,commentators_uniq,comments_obscene_cnt,video_age
19119,♫♪Мы расстаемся ♫♪ Бутырка new2019,2.0,0.0,11.0,shanson,бутырка,1107.0,NaN,NaN,44
19120,❤ 2 ЧАСА ❤ МОЦАРТ Для Младенцев - Колыбельная ...,94.0,431.0,1837.0,classic,classical_channel,391836.0,37.0,1.0,239
19121,モスクワライブショー ' 17,4872.0,15494.0,30603.0,rap,элджей,1187340.0,1788.0,352.0,339
19122,舞梅鬼 - 新年好宝贝 / Mumiy Troll - Happy New Year ...,59.0,10.0,260.0,rock,мумий_тролль,10147.0,19.0,0.0,997
19123,🎄#премьера песни!!! 2019г(вы не спешите говори...,1.0,0.0,22.0,shanson,бутырка,1566.0,NaN,NaN,65

In [30]:
df.shape

(19124, 10)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19124 entries, 0 to 19123
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 19124 non-null  object
 1   commentCount          18914 non-null  float64
 2   dislikeCount          18850 non-null  float64
 3   likeCount             18850 non-null  float64
 4   music_style           19124 non-null  object
 5   performer             19124 non-null  object
 6   viewCount             19123 non-null  float64
 7   commentators_uniq     12314 non-null  float64
 8   comments_obscene_cnt  12314 non-null  float64
 9   video_age             19124 non-null  int64
dtypes: float64(6), int64(1), object(3)
memory usage: 1.5+ MB

In [35]:
df.isna().sum().sort_values(ascending = False)

commentators_uniq       6810
comments_obscene_cnt    6810
dislikeCount             274
likeCount                274
commentCount             210
viewCount                  1
title                      0
music_style                0
performer                  0
video_age                  0
dtype: int64

In [38]:
df.iloc[5:24, :]

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,title,commentCount,dislikeCount,likeCount,music_style,performer,viewCount,commentators_uniq,comments_obscene_cnt,video_age
5,"""Feelin High"" Сергей Лазарев Sergey Lazarev live",7.0,7.0,87.0,popsa,лазарев,9217.0,6.0,0.0,3179
6,"""Girlfriend"" Сергей Лазарев (SERGEY)",88.0,69.0,1566.0,popsa,лазарев,449891.0,63.0,1.0,4013
7,"""Heartbeat"" Сергей Лазарев (Sergey Lazarev)",168.0,101.0,4091.0,popsa,лазарев,763611.0,130.0,0.0,2948
8,"""Hey Tovarish"" Video Shooting",10.0,1.0,34.0,rock,мумий_тролль,3815.0,9.0,0.0,2539
9,"""LAZERBOY"" Сергей Лазарев (SERGEY) feat. TИМАТ...",422.0,229.0,4137.0,popsa,лазарев,629212.0,223.0,6.0,3765
10,"""LAZERBOY""( Michael Yousher videoremix) Сергей...",5.0,4.0,141.0,popsa,лазарев,35902.0,5.0,1.0,3608
11,"""Lost without your love"" Сергей Лазарев (SERGEY)",189.0,102.0,2599.0,popsa,лазарев,582159.0,119.0,4.0,3308
12,"""Love Radio"": Съемки клипа НЮШИ ""Наедине""",25.0,14.0,283.0,popsa,нюша,58496.0,24.0,0.0,2165
13,"""Ru Music"": НЮША сняла новый клип!",12.0,4.0,87.0,popsa,нюша,14780.0,9.0,0.0,2180
14,"""Ru Новости"": НЮША чудом вернулась в Москву!",5.0,5.0,49.0,popsa,нюша,4625.0,5.0,1.0,2179
15,"""SOS Матросу!"" - тизер фильма",10.0,4.0,68.0,rock,мумий_тролль,7632.0,5.0,0.0,1739
16,"""STEREO"" (LIVE) Сергей Лазарев (SERGEY)",30.0,10.0,541.0,popsa,лазарев,117765.0,26.0,1.0,3522
17,"""Shattered dreams"" Сергей Лазарев (SERGEY)",57.0,28.0,961.0,popsa,лазарев,109955.0,35.0,1.0,3603
18,"""Tv or radio"" Сергей Лазарев (SERGEY)",627.0,157.0,3714.0,popsa,лазарев,634676.0,277.0,7.0,4189
19,"""You Are The Only One"" - Sergey Lazarev /MadWa...",156.0,96.0,2203.0,popsa,лазарев,165878.0,101.0,0.0,1056
20,"""Аве Мария"" Весь зал плакал. Вика 11 лет",3865.0,8603.0,47974.0,classic,classical_channel,10674427.0,1568.0,11.0,2636
21,"""Антоха МС - Советы для молодожёнов /2017/""",11.0,12.0,288.0,indi,антоха_мс,8316.0,10.0,0.0,529
22,"""Большая семья"" Игоря Крутого - часть 1",0.0,9.0,44.0,estrada,николаев,50344.0,NaN,NaN,3051
23,"""Большая семья"" Игоря Крутого - часть 2",1.0,1.0,27.0,estrada,николаев,23952.0,1.0,0.0,3051

In [39]:
cols = ['title', 'commentCount', 'likeCount', 'music_style']
ndf = df[cols]
ndf

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,title,commentCount,likeCount,music_style
0,"""#2Маши ""Свободные линии""",34.0,1402.0,popsa
1,"""ALARM"" СЕРГЕЙ ЛАЗАРЕВ ( SERGEY LAZAREV )",NaN,10532.0,popsa
2,"""EARTH SONG"" SERGEY LAZAREV. DEDICATED TO MIC...",26.0,269.0,popsa
3,"""Earth song"" премия МУЗ-тВ 2010 (LIVE)",12.0,163.0,popsa
4,"""FAKE"" СЕРГЕЙ ЛАЗАРЕВ (SERGEY)",46.0,597.0,popsa
...,...,...,...,...
19119,♫♪Мы расстаемся ♫♪ Бутырка new2019,2.0,11.0,shanson
19120,❤ 2 ЧАСА ❤ МОЦАРТ Для Младенцев - Колыбельная ...,94.0,1837.0,classic
19121,モスクワライブショー ' 17,4872.0,30603.0,rap
19122,舞梅鬼 - 新年好宝贝 / Mumiy Troll - Happy New Year ...,59.0,260.0,rock
19123,🎄#премьера песни!!! 2019г(вы не спешите говори...,1.0,22.0,shanson

In [40]:
ndf.iloc[23:101, :]

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,title,commentCount,likeCount,music_style
23,"""Большая семья"" Игоря Крутого - часть 2",1.0,27.0,estrada
24,"""Большая семья"" Игоря Крутого - часть 3",0.0,79.0,estrada
25,"""Большая семья"" Игоря Крутого - часть 4",1.0,24.0,estrada
26,"""Большая семья"" Игоря Крутого - часть 6",1.0,74.0,estrada
27,"""Большая семья"" Игоря Крутого - часть 7",0.0,20.0,estrada
...,...,...,...,...
96,"""Новая волна 2016"" Творческий вечер Олега Газм...",94.0,1048.0,estrada
97,"""Ногу Свело!"" - SOS in the Ass",8.0,127.0,rock
98,"""Океаны"" (acoustic home version)",10.0,NaN,estrada
99,"""Остров Юрий""",1.0,11.0,estrada
100,"""ПОДВЕНЕЧНОЕ БЕЛОЕ ПЛАТЬЕ - 2"" гр. Воровайки, ...",3.0,2.0,shanson

In [45]:
new_index = range(23, 101)
ndf.loc[new_index, :]

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,title,commentCount,likeCount,music_style
23,"""Большая семья"" Игоря Крутого - часть 2",1.0,27.0,estrada
24,"""Большая семья"" Игоря Крутого - часть 3",0.0,79.0,estrada
25,"""Большая семья"" Игоря Крутого - часть 4",1.0,24.0,estrada
26,"""Большая семья"" Игоря Крутого - часть 6",1.0,74.0,estrada
27,"""Большая семья"" Игоря Крутого - часть 7",0.0,20.0,estrada
...,...,...,...,...
96,"""Новая волна 2016"" Творческий вечер Олега Газм...",94.0,1048.0,estrada
97,"""Ногу Свело!"" - SOS in the Ass",8.0,127.0,rock
98,"""Океаны"" (acoustic home version)",10.0,NaN,estrada
99,"""Остров Юрий""",1.0,11.0,estrada
100,"""ПОДВЕНЕЧНОЕ БЕЛОЕ ПЛАТЬЕ - 2"" гр. Воровайки, ...",3.0,2.0,shanson

In [46]:
ndf[ndf['likeCount'] > 1000]

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,title,commentCount,likeCount,music_style
0,"""#2Маши ""Свободные линии""",34.0,1402.0,popsa
1,"""ALARM"" СЕРГЕЙ ЛАЗАРЕВ ( SERGEY LAZAREV )",NaN,10532.0,popsa
6,"""Girlfriend"" Сергей Лазарев (SERGEY)",88.0,1566.0,popsa
7,"""Heartbeat"" Сергей Лазарев (Sergey Lazarev)",168.0,4091.0,popsa
9,"""LAZERBOY"" Сергей Лазарев (SERGEY) feat. TИМАТ...",422.0,4137.0,popsa
...,...,...,...,...
19114,♫ The Greatest Hits of Russian Classical Music...,81.0,2216.0,classic
19115,♫ Классическая музыка для детей (Classical mus...,464.0,14144.0,classic
19117,♫♡ Сборник Лучших Мелодий - Наслаждайтесь Восх...,2881.0,58429.0,classic
19120,❤ 2 ЧАСА ❤ МОЦАРТ Для Младенцев - Колыбельная ...,94.0,1837.0,classic
19121,モスクワライブショー ' 17,4872.0,30603.0,rap

In [47]:
ndf[(ndf['likeCount'] > 1000) & ((ndf['music_style'] == 'popsa') | (ndf['music_style'] == 'rock') | (ndf['music_style'] == 'indi'))]

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,title,commentCount,likeCount,music_style
0,"""#2Маши ""Свободные линии""",34.0,1402.0,popsa
1,"""ALARM"" СЕРГЕЙ ЛАЗАРЕВ ( SERGEY LAZAREV )",NaN,10532.0,popsa
6,"""Girlfriend"" Сергей Лазарев (SERGEY)",88.0,1566.0,popsa
7,"""Heartbeat"" Сергей Лазарев (Sergey Lazarev)",168.0,4091.0,popsa
9,"""LAZERBOY"" Сергей Лазарев (SERGEY) feat. TИМАТ...",422.0,4137.0,popsa
...,...,...,...,...
19054,гр. Ленинград — Песня счастья / Leningrad — So...,95.0,1127.0,rock
19055,гр. Ленинград — Последняя осень / Leningrad — ...,191.0,2243.0,rock
19085,монеточка - Новая форма капитала,229.0,4711.0,indi
19100,"пой, Минск!",NaN,1774.0,rock
19110,тёлка из клипа-это я. iowa,106.0,1064.0,popsa

In [49]:
ndf[(df['performer'] == 'лазарев') & (df['likeCount'] > 10_000) & (df['video_age'] < 60)]

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)

,title,commentCount,likeCount,music_style
3819,Sergey Lazarev - Scream - Eurovision 2019 ( Ru...,16956.0,99666.0,popsa

In [51]:
ndf[(~ndf['music_style'].isin(['popsa', 'rock', 'classic', 'shanson'])) & ((ndf['likeCount'] > 5000) | (ndf['commentCount'] > 1000))]

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)

,title,commentCount,likeCount,music_style
286,#ГазгольдерФильм,4676.0,49038.0,rap
287,#ДАВАЙДОСВИДАНИЯ (OFFICIAL TRACK),770.0,6830.0,rap
288,#ДАВАЙДОСВИДАНИЯ (OFFICIAL VIDEO),28443.0,191561.0,rap
319,#ЭТОМОЕ (Участники конкурса),586.0,7971.0,rap
323,#тамада (Сингл),19.0,8023.0,rap
...,...,...,...,...
18868,"Юлия Проскурякова, Елена Есенина и Максим Галк...",225.0,9342.0,estrada
18900,Я АКТЕР / ПРИКОЛ НА СЪЕМКАХ :),213.0,5781.0,rap
18945,Я лиза,448.0,11589.0,indi
19040,в гостях у Антохи МС,249.0,10929.0,indi
19121,モスクワライブショー ' 17,4872.0,30603.0,rap

In [77]:
df_lazarev = df[(df['performer'] == 'лазарев') & (df['likeCount'] > 0)] #get the columns lazarev and likeCount
max_index = df_lazarev['likeCount'].idxmax() #get the index of the row that has the biggest number in likeCount
max_Lazarev_like = df.loc[max_index, 'likeCount'] #find that index in df and return value
print(f"Lazarev's maximum number of likes is: {max_Lazarev_like}")

Lazarev's maximum number of likes is: 334552.0

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)

In [80]:
df_filtered = df[['title', 'viewCount']]
m_index = df_filtered['viewCount'].idxmax()
max_views_title = df.loc[m_index, 'title']
print(f"The title with maximum number of views is: {max_views_title}")

The title with maximum number of views is: Miyagi & Эндшпиль feat. Рем Дигга - I Got Love (Official Video)

In [100]:
df_eldjey = df[(df['performer'] == 'элджей') & (df['likeCount'] > 0)]
df_eldjey_mean = df_eldjey['likeCount'].mean()
eldjey_titles_above_average = df[(df['performer'] == 'элджей') & (df['likeCount'] > df_eldjey_mean)]
print(f"The performer 'eldjey' gets {df_eldjey_mean:.0f} likes on average.")
print("His titles that have likes above average are:")
for index, row in eldjey_titles_above_average.iterrows():
    print(f"{row['title']} - the number of likes: {row['likeCount']}.")

The performer 'eldjey' gets 55897 likes on average.
His titles that have likes above average are:
Черное Кино & Элджей - Гости из будущего - the number of likes: 65271.0.
Элджей - 360° - the number of likes: 146381.0.
Элджей & Feduk - Розовое вино - the number of likes: 604766.0.
Элджей & Sorta - Aqua - the number of likes: 137173.0.
Элджей - 1love - the number of likes: 109360.0.
Элджей - 1love - the number of likes: 71178.0.
Элджей - 360° - the number of likes: 412504.0.
Элджей - California - the number of likes: 181419.0.
Элджей - Hey, Guys - the number of likes: 203876.0.
Элджей - Suzuki - the number of likes: 193707.0.
Элджей - Минимал - the number of likes: 400063.0.
Элджей - Минимал - the number of likes: 233847.0.
Элджей - Рваные джинсы - the number of likes: 593238.0.

In [108]:
print("The number of unique_titles is:", df['title'].nunique())
print("The number of unique_performers is:", df['performer'].nunique())
print("The number of unique_styles is:", df['music_style'].nunique())

The number of unique_titles is: 18029
The number of unique_performers is: 111
The number of unique_styles is: 7

In [111]:
print("The unique music styles are:", df.music_style.unique())

The unique music styles are: ['popsa' 'rock' 'classic' 'indi' 'estrada' 'shanson' 'rap']

In [112]:
df['total_reaction_count'] = df['likeCount'] + df['dislikeCount']
df

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,title,commentCount,dislikeCount,likeCount,music_style,performer,viewCount,commentators_uniq,comments_obscene_cnt,video_age,total_reaction_count
0,"""#2Маши ""Свободные линии""",34.0,43.0,1402.0,popsa,2маши,214301.0,24.0,0.0,1141,1445.0
1,"""ALARM"" СЕРГЕЙ ЛАЗАРЕВ ( SERGEY LAZAREV )",NaN,690.0,10532.0,popsa,лазарев,2221419.0,NaN,NaN,3217,11222.0
2,"""EARTH SONG"" SERGEY LAZAREV. DEDICATED TO MIC...",26.0,10.0,269.0,popsa,лазарев,40327.0,23.0,0.0,3546,279.0
3,"""Earth song"" премия МУЗ-тВ 2010 (LIVE)",12.0,7.0,163.0,popsa,лазарев,11907.0,11.0,0.0,3189,170.0
4,"""FAKE"" СЕРГЕЙ ЛАЗАРЕВ (SERGEY)",46.0,19.0,597.0,popsa,лазарев,91483.0,33.0,1.0,3361,616.0
...,...,...,...,...,...,...,...,...,...,...,...
19119,♫♪Мы расстаемся ♫♪ Бутырка new2019,2.0,0.0,11.0,shanson,бутырка,1107.0,NaN,NaN,44,11.0
19120,❤ 2 ЧАСА ❤ МОЦАРТ Для Младенцев - Колыбельная ...,94.0,431.0,1837.0,classic,classical_channel,391836.0,37.0,1.0,239,2268.0
19121,モスクワライブショー ' 17,4872.0,15494.0,30603.0,rap,элджей,1187340.0,1788.0,352.0,339,46097.0
19122,舞梅鬼 - 新年好宝贝 / Mumiy Troll - Happy New Year ...,59.0,10.0,260.0,rock,мумий_тролль,10147.0,19.0,0.0,997,270.0
19123,🎄#премьера песни!!! 2019г(вы не спешите говори...,1.0,0.0,22.0,shanson,бутырка,1566.0,NaN,NaN,65,22.0

In [117]:
print(f"The mean of reactions is: {df['total_reaction_count'].mean():.0f}")

The mean of reactions is: 6480